/*
 * File: app/view/main/Main.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.main.Main', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main.main',

    requires: [
        'Admin.view.main.MainViewModel',
        'Admin.view.main.MainViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.button.Segmented'
    ],

    controller: 'main.main',
    viewModel: {
        type: 'main.main'
    },
    cls: 'sencha-dash-viewport',
    itemId: 'mainView',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    listeners: {
        render: 'onMainViewRender'
    },
    items: [
        {
            xtype: 'toolbar',
            flex: 1,
            cls: 'sencha-dash-dash-headerbar shadow',
            height: 64,
            itemId: 'headerBar',
            items: [
                {
                    xtype: 'component',
                    reference: 'senchaLogo',
                    cls: 'sencha-logo',
                    html: '<div class="main-logo"><img src="resources/images/company-logo.png">Sencha</div>',
                    width: 250
                },
                {
                    xtype: 'button',
                    handler: 'onToggleNavigationSize',
                    id: 'main-navigation-btn',
                    margin: '0 0 0 8',
                    iconCls: 'x-fa fa-navicon'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'segmentedbutton',
                    platformConfig: {
                        ie9m: {
                            hidden: true
                        }
                    },
                    margin: '0 16 0 0',
                    items: [
                        {
                            enableToggle: true,
                            iconCls: 'x-fa fa-desktop',
                            pressed: true
                        },
                        {
                            handler: 'onSwitchToModern',
                            iconCls: 'x-fa fa-tablet',
                            tooltip: 'Switch to modern toolkit'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    href: '#searchresults',
                    hrefTarget: '_self',
                    iconCls: 'x-fa fa-search',
                    tooltip: 'See latest search'
                },
                {
                    xtype: 'button',
                    href: '#email',
                    hrefTarget: '_self',
                    iconCls: 'x-fa fa-envelope',
                    tooltip: 'Check your email'
                }
            ]
        }
    ]

});