/*
 * File: app/view/pages/ErrorBase.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.pages.ErrorBase', {
    extend: 'Ext.window.Window',
    alias: 'widget.pages.errorbase',

    requires: [
        'Admin.view.pages.ErrorBaseViewModel'
    ],

    viewModel: {
        type: 'pages.errorbase'
    },
    modal: true,
    cls: 'error-page-container',
    closable: false,
    title: 'Sencha',
    titleAlign: 'center',
    maximized: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    }

});